# Terraform Infrastructure Configuration
# This file defines all infrastructure resources for the Mojaloop performance testing environment

# AWS Configuration
aws:
  profile: gtmlab
  region: eu-west-2
  availability_zone: eu-west-2a

# Project Configuration
project:
  name: perf-test-202509171524
  environment: perf-test

# SSH Configuration
ssh:
  key_name: ndelma-gtm-202504091000
  # public_key_path: ~/.ssh/ndelma-gtm-202504091000.pub  # Optional: if you want Terraform to manage the key

# Network Configuration
network:
  vpc:
    cidr: 10.110.0.0/16
    enable_dns_hostnames: true
    enable_dns_support: true

  subnets:
    public:
      name: public-subnet
      cidr: 10.110.1.0/24
      map_public_ip: true  # Only for bastion

    private:
      name: private-subnet
      cidr: 10.110.2.0/24
      map_public_ip: false

# Security Configuration
security:
  # Bastion security group - allows SSH from internet
  bastion:
    ingress_rules:
      - port: 22
        protocol: tcp
        cidr_blocks:
          - 0.0.0.0/0  # Replace with your specific IP ranges for better security
        description: "SSH access to bastion"

    egress_rules:
      - port: 0-65535
        protocol: -1
        cidr_blocks:
          - 0.0.0.0/0
        description: "Allow all outbound internet traffic"

  # Internal nodes security group - shared by switch and DFSP nodes
  internal:
    ingress_rules:
      # SSH from bastion only
      - port: 22
        protocol: tcp
        source: bastion_sg  # Reference to bastion security group
        description: "SSH from bastion"

      # MicroK8s cluster ports
      - port: 16443
        protocol: tcp
        source: self  # Allow from same security group
        description: "MicroK8s API server"

      - port: 25000
        protocol: tcp
        source: self
        description: "MicroK8s clustering"

      - port: 4789
        protocol: udp
        source: self
        description: "VXLAN for pod networking"

      - port: 179
        protocol: tcp
        source: self
        description: "Calico BGP"

      - port: 12379-12380
        protocol: tcp
        source: self
        description: "etcd"

      # NodePort range (optional - only if external access needed)
      - port: 30000-32767
        protocol: tcp
        source: bastion_sg  # Or specific CIDR if needed
        description: "NodePort range"

      # Allow all traffic between nodes in the same security group
      - port: 0-65535
        protocol: -1
        source: self
        description: "All internal cluster traffic"

    egress_rules:
      - port: 0-65535
        protocol: -1
        cidr_blocks:
          - 0.0.0.0/0
        description: "Allow all outbound internet traffic (for package downloads, updates, etc.)"

# Virtual Machines Configuration
vms:
  # Ubuntu 24.04 LTS AMI
  default_ami: ami-044415bb13eee2391

  # Bastion Host
  bastion:
    enabled: true
    name: bastion
    instance_type: t3.small
    root_volume:
      size: 16
      type: gp3
      delete_on_termination: true
    tags:
      Role: bastion
      Purpose: "SSH jump host"
    # Terraform lifecycle policy
    lifecycle:
      prevent_destroy: false
      create_before_destroy: false
      ignore_changes: []

  # Switch Nodes (Mojaloop Core) - HA cluster with 3 nodes
  switch:
    # Default configuration for all switch nodes
    defaults:
      instance_type: m4.2xlarge
      root_volume:
        size: 128
        type: gp3
        delete_on_termination: true
      lifecycle:
        prevent_destroy: false
        create_before_destroy: false
        ignore_changes: []

    # Individual switch node configurations for 3-node HA cluster
    instances:
      - name: sw1-n1
        instance_type: m4.2xlarge  # Can override default
        tags:
          Role: ml-sw
          NodeNumber: "1"
          K8sRole: "mixed"

      - name: sw1-n2
        instance_type: m4.2xlarge
        tags:
          Role: ml-sw
          NodeNumber: "2"
          K8sRole: "mixed"

      - name: sw1-n3
        instance_type: m4.2xlarge
        tags:
          Role: ml-sw
          NodeNumber: "3"
          K8sRole: "mixed"

  # DFSP Nodes (Digital Financial Service Providers)
  dfsps:
    # Default configuration for all DFSPs (can be overridden per DFSP)
    defaults:
      instance_type: m4.xlarge
      root_volume:
        size: 128
        type: gp3
        delete_on_termination: true
      lifecycle:
        prevent_destroy: false
        create_before_destroy: false
        ignore_changes: []

    # Individual DFSP configurations
    instances:
      - name: fsp101
        instance_type: m4.xlarge  # Can override default
        tags:
          Role: ml-dfsp
          NodeNumber: "101"

      - name: fsp102
        instance_type: m4.xlarge
        tags:
          Role: ml-dfsp
          NodeNumber: "102"

      - name: fsp103
        instance_type: m4.xlarge
        tags:
          Role: ml-dfsp
          NodeNumber: "103"

      # - name: fsp104
      #   instance_type: m4.xlarge
      #   tags:
      #     Role: ml-dfsp
      #     NodeNumber: "104"

      # - name: fsp105
      #   instance_type: m4.xlarge
      #   tags:
      #     Role: ml-dfsp
      #     NodeNumber: "105"

      # - name: fsp106
      #   instance_type: m4.xlarge
      #   tags:
      #     Role: ml-dfsp
      #     NodeNumber: "106"

      # - name: fsp107
      #   instance_type: m4.xlarge
      #   tags:
      #     Role: ml-dfsp
      #     NodeNumber: "107"

      # - name: fsp108
      #   instance_type: m4.xlarge
      #   root_volume:
      #     size: 128  # Override for larger disk
      #     type: gp3
      #     delete_on_termination: true
      #   tags:
      #     Role: ml-dfsp
      #     NodeNumber: "108"

# Terraform Backend Configuration (for state management)
terraform:
  backend:
    type: s3  # or local
    s3:
      bucket: "terraform-state-${project.name}"  # Will be interpolated
      key: "infrastructure/terraform.tfstate"
      region: "${aws.region}"
      profile: "${aws.profile}"
      encrypt: true
      dynamodb_table: "terraform-state-lock-${project.name}"

  # Resource lifecycle policies
  lifecycle_defaults:
    prevent_destroy: false  # Set to true in production
    create_before_destroy: false
    ignore_changes: []  # Add attributes to ignore, e.g., ["ami", "user_data"]

# Output Configuration
outputs:
  generate_ansible_inventory: true
  inventory_file: "./inventory.yaml"
  generate_ssh_config: true
  ssh_config_file: "./ssh_config"