---
- name: Configure MicroK8s FSP Single-Node Clusters
  hosts: dfsps
  become: yes
  gather_facts: yes
  vars:
    config: "{{ lookup('file', '../../../02-infrastructure/config.yaml') | from_yaml }}"

  tasks:
    - name: Enable MicroK8s addons for FSP clusters
      shell: "microk8s enable {{ item }}"
      loop: "{{ config.k8s.addons.fsp_clusters }}"
      register: addon_result
      changed_when: "'is already enabled' not in addon_result.stdout"
      retries: 3
      delay: 10

    - name: Wait for all addons to be ready
      shell: microk8s status --wait-ready
      changed_when: false
      retries: 10
      delay: 30

    - name: Verify single-node cluster status
      shell: microk8s kubectl get nodes
      register: node_status
      changed_when: false

    - name: Display FSP cluster status
      debug:
        msg: |
          FSP Cluster: {{ inventory_hostname }}
          Status: {{ node_status.stdout }}

    - name: Label FSP node
      shell: |
        microk8s kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/control-plane=true --overwrite
        microk8s kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker=true --overwrite
        microk8s kubectl label node {{ inventory_hostname }} fsp-id={{ inventory_hostname }} --overwrite
      changed_when: false

    - name: Create FSP namespace
      shell: |
        microk8s kubectl create namespace {{ inventory_hostname }}-apps --dry-run=client -o yaml | microk8s kubectl apply -f -
      changed_when: false