#!/usr/bin/env bash
#
# Regenerate the single shared lab cert bundle used for mTLS between switch
# and DFSPs, and emit two Secret manifests:
#   - switch-tls-secret.yaml   (Secret in istio-system, used by Istio)
#   - dfsp-tls-secret.yaml     (Secret in dfsps on every DFSP cluster,
#                                  mounted by the SDK via tlsSecretName)
#
# Algorithm: ECDSA P-256 (default — recommended for prod too) or P-384.
#   - P-256: 128-bit security (= RSA 3072), FIPS 186-4, TLS 1.3 baseline curve.
#     Fastest practical option: BoringSSL (Envoy) has an assembly path for P-256
#     but not P-384, so P-256 sign is ~5-8x faster than P-384. Keep this unless a
#     specific mandate requires more.
#   - P-384: 192-bit security (= RSA 7680). Use ONLY when a written compliance
#     baseline requires it (e.g. NSA CNSA). PCI-DSS does NOT require P-384 — it
#     requires "strong cryptography", which P-256 satisfies. Costs ~5-8x more
#     handshake CPU; with HTTP keepalive this is amortised in steady state but
#     bites during connection-churn (pod restarts, outlier ejection, 2000 TPS).
#   Set CURVE=prime256v1 (default) or CURVE=secp384r1.
#
# Cert validity: with TLS-version + cipher hardening enforced at the Istio layer
# (Gateway tls + meshConfig.tlsDefaults in common/istiod-values.yaml), and
# correct X.509 keyUsage below (CA: keyCertSign,cRLSign; leaf: digitalSignature).
#
# Lab-only. Run once per clone (the two generated Secret manifests are
# git-ignored, not committed) and re-run to rotate. Do not port this
# shared-cert pattern outside of perf test clusters.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORK="$(mktemp -d)"
trap "rm -rf $WORK" EXIT

cd "$WORK"

# P-256 for perf lab (default); override with CURVE=secp384r1 for production.
CURVE="${CURVE:-prime256v1}"
echo "Using curve: $CURVE"

# CA — explicit v3 extensions. A bare `req -x509` omits keyUsage, so a strict
# verifier can reject certs signed by it. basicConstraints CA:TRUE pathlen:0
# (signs leaves only) + keyUsage keyCertSign,cRLSign are the correct, minimal
# CA usages.
openssl ecparam -name "$CURVE" -genkey -noout -out ca.key 2>/dev/null
cat > ca.conf <<'EOF'
[req]
distinguished_name = dn
x509_extensions    = v3_ca
prompt             = no

[dn]
CN = mojaloop-perf-lab-ca

[v3_ca]
basicConstraints     = critical, CA:TRUE, pathlen:0
keyUsage             = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash
EOF
openssl req -x509 -new -nodes -key ca.key -sha256 -days 3650 \
  -config ca.conf -out ca.crt

# Leaf with SANs
openssl ecparam -name "$CURVE" -genkey -noout -out leaf.key 2>/dev/null
cat > csr.conf <<'EOF'
[req]
distinguished_name = dn
req_extensions     = req_ext
prompt             = no

[dn]
CN = mojaloop-perf-mtls

[req_ext]
# ECDSA cert used with ECDHE (TLS 1.2/1.3): the key SIGNS the handshake, it does
# not do key agreement. keyAgreement applies only to static-ECDH suites, which
# are never negotiated here — dropped. digitalSignature covers both the server
# (CertificateVerify / signed key exchange) and client-auth roles of this shared
# cert. CA:FALSE marks it as an end-entity (leaf) cert.
basicConstraints = critical, CA:FALSE
keyUsage         = critical, digitalSignature
extendedKeyUsage = serverAuth, clientAuth
subjectAltName   = @alt_names

[alt_names]
DNS.1  = account-lookup-service.local
DNS.2  = quoting-service.local
DNS.3  = ml-api-adapter.local
DNS.4  = sim-fsp201.local
DNS.5  = sim-fsp202.local
DNS.6  = sim-fsp203.local
DNS.7  = sim-fsp204.local
DNS.8  = sim-fsp205.local
DNS.9  = sim-fsp206.local
DNS.10 = sim-fsp207.local
DNS.11 = sim-fsp208.local
EOF

openssl req -new -key leaf.key -out leaf.csr -config csr.conf
openssl x509 -req -in leaf.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
  -out leaf.crt -days 3650 -sha256 -extfile csr.conf -extensions req_ext 2>/dev/null

CA_B64=$(base64 < ca.crt  | tr -d '\n')
CRT_B64=$(base64 < leaf.crt | tr -d '\n')
KEY_B64=$(base64 < leaf.key | tr -d '\n')

cat > "${SCRIPT_DIR}/switch-tls-secret.yaml" <<EOF
# Generated by regen-certs.sh — do not edit by hand.
# Referenced by manifests/mtls/switch-inbound.yaml (Gateway credentialName)
# and, after being copied into the mojaloop namespace by the mtls_switch
# role, by the rendered sidecar DestinationRules (Leg B origination).
apiVersion: v1
kind: Secret
metadata:
  name: switch-mtls-creds
  namespace: istio-system
  labels: { app: mtls-lab }
type: kubernetes.io/tls
data:
  ca.crt:  ${CA_B64}
  tls.crt: ${CRT_B64}
  tls.key: ${KEY_B64}
EOF

cat > "${SCRIPT_DIR}/dfsp-tls-secret.yaml" <<EOF
# Generated by regen-certs.sh — do not edit by hand.
# Applied to the dfsps namespace on every DFSP cluster. The mojaloop-simulator
# Helm chart mounts this as /secrets/* when values set
# simulators.fspNNN.config.schemeAdapter.secrets.tlsSecretName: mtls-shared-creds
apiVersion: v1
kind: Secret
metadata:
  name: mtls-shared-creds
  namespace: dfsps
  labels: { app: mtls-lab }
type: Opaque
data:
  inbound-cacert.pem:  ${CA_B64}
  inbound-cert.pem:    ${CRT_B64}
  inbound-key.pem:     ${KEY_B64}
  outbound-cacert.pem: ${CA_B64}
  outbound-cert.pem:   ${CRT_B64}
  outbound-key.pem:    ${KEY_B64}
EOF

echo "Wrote:"
echo "  ${SCRIPT_DIR}/switch-tls-secret.yaml"
echo "  ${SCRIPT_DIR}/dfsp-tls-secret.yaml"
echo ""
echo "Leaf cert summary:"
openssl x509 -in leaf.crt -noout -subject -issuer -ext subjectAltName
