---
# Let's Encrypt Staging Issuer (for testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Staging server for testing
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@example.com  # CHANGE THIS to your email
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx

---
# Let's Encrypt Production Issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Production server
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@example.com  # CHANGE THIS to your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

---
# Certificate for mTLS endpoints
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mojaloop-mtls-cert
  namespace: mojaloop  # Adjust namespace as needed
spec:
  secretName: mojaloop-mtls-tls
  issuerRef:
    name: letsencrypt-staging  # Use letsencrypt-prod when ready
    kind: ClusterIssuer
  dnsNames:
  - account-lookup-service.local  # CHANGE to your actual domain
  - quoting-service.local          # CHANGE to your actual domain
  - ml-api-adapter.local           # CHANGE to your actual domain
