apiVersion: v2
description: "Helm Chart for the Mojaloop (SDK-based) Simulator"
name: mojaloop-simulator
version: 1.0.0
appVersion: "sdk-scheme-adapter: v24.6.2; mojaloop-simulator: v15.3.0; thirdparty-sdk: v15.1.3"
dependencies:
  - name: common
    repository: "https://mojaloop.github.io/charts/repo"
    version: 3.1.3
    tags:
      - moja-common
maintainers:
  - name: Shashikant Hirugade
    email: shashi.mojaloop@gmail.com
