
# Default values for mojaloop-k6-operator
# k6Operator:
#   enabled: true
#   watchNamespace: ""

image:
  repository: grafana/k6
  tag: "0.49.0"
  pullPolicy: IfNotPresent

parallelism: 1

k6:
  targetTxnCount: 10
  targetTps: 1
  fspMode: "8-DFSP"
  abortOnError: true
  transferAmount: "1"
  currency: "USD"
  fspPairs:
    - source: fsp1
      dest: fsp2
      weight: 0.5
    - source: fsp3
      dest: fsp4
      weight: 0.5
  fspConfig: |
    {
      "fsp1": { "id": "fsp1", "msisdn": "17039811910", "baseUrl": "http://sim-fsp1.local/sim/fsp1/outbound", "startMsisdn": "17039811911" },
      "fsp2": { "id": "fsp2", "msisdn": "17039811911", "baseUrl": "http://sim-fsp2.local/sim/fsp2/outbound", "startMsisdn": "17039811921" },
      "fsp3": { "id": "fsp3", "msisdn": "17039811912", "baseUrl": "http://sim-fsp3.local/sim/fsp3/outbound", "startMsisdn": "37039811911" },
      "fsp4": { "id": "fsp4", "msisdn": "17039811913", "baseUrl": "http://sim-fsp4.local/sim/fsp4/outbound", "startMsisdn": "47039811921" },
    }
resources:
  limits:
    cpu: "2"
    memory: "1Gi"
  requests:
    cpu: "1"
    memory: "500Mi"

# Optional: InfluxDB output configuration
# output:
#   enabled: false
#   type: "influxdb"
#   url: "http://influxdb:8086"
#   db: "k6"