# Longhorn Storage Configuration for Mojaloop Performance Testing
# This configuration ensures Longhorn can run on all nodes regardless of taints

# Global settings
global:
  tolerations:
    # Tolerate all taints to ensure storage is available on all nodes
    - operator: "Exists"

# CSI Driver settings - must run on all nodes
csi:
  kubeletRootDir: "/var/snap/microk8s/common/var/lib/kubelet"
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

# Default Longhorn settings
defaultSettings:
  createDefaultDiskLabeledNodesOnly: false
  replicaSoftAntiAffinity: true
  defaultReplicaCount: 1
  nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"

  # Toleration settings for Longhorn system components
  taintToleration: "dedicated=kafka:NoSchedule;dedicated=mysql:NoSchedule;dedicated=monitoring:NoSchedule"
  systemManagedComponentsNodeSelector: ""  # Allow on all nodes

# Longhorn Manager
longhornManager:
  tolerations:
    - operator: "Exists"
  nodeSelector: {}  # Can run on any node

# Longhorn Driver
longhornDriver:
  tolerations:
    - operator: "Exists"
  nodeSelector: {}  # Must run on all nodes (DaemonSet)

# Longhorn UI (optional)
longhornUI:
  enabled: true
  nodeSelector:
    workload-class.mojaloop.io/MONITORING: "true"  # Deploy UI on monitoring node
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"

# Instance Manager - runs where volumes are needed
instanceManager:
  tolerations:
    - operator: "Exists"

# Engine settings
engine:
  tolerations:
    - operator: "Exists"

# Replica settings
replica:
  tolerations:
    - operator: "Exists"