# Values for perffsp1 k6 instance
# image:
#   repository: grafana/k6
#   tag: "0.49.0"
#   pullPolicy: IfNotPresent

k6:
  targetTxnCount: 100
  fspMode: "8-DFSP"
  abortOnError: true
  callbackTimeoutMs: 10000
  transferAmount: "100"
  currency: "USD"
  alsEndpoint: "http://moja-account-lookup-service"
  quotesEndpoint: "http://moja-quoting-service"
  transfersEndpoint: "http://moja-ml-api-adapter-service"
  targetTps: 70
  fspPairs:
    - source: perffsp1
      dest: perffsp2
      weight: 0.70 # 490 TPS
    - source: perffsp1
      dest: perffsp4
      weight: 0.10 # 70 TPS
    - source: perffsp1
      dest: perffsp6
      weight: 0.10 # 70 TPS
    - source: perffsp1
      dest: perffsp8
      weight: 0.10 # 70 TPS

resources:
  limits:
    cpu: "1"
    memory: "500Mi"
  requests:
    cpu: "1"
    memory: "500Mi"

nodeSelector:
  fspiop-dfsp: perffsp1

# output:
#   enabled: false
#   type: "influxdb"
#   url: "http://influxdb.influxdb.svc.cluster.local:8086"
#   db: "k6"