#!/usr/bin/env bash
#
# Regenerate the single shared lab cert bundle used for mTLS between switch
# and DFSPs, and emit two Secret manifests:
#   - 04-switch-tls-secret.yaml   (Secret in istio-system, used by Istio)
#   - 04-dfsp-tls-secret.yaml     (Secret in dfsps on every DFSP cluster,
#                                  mounted by the SDK via tlsSecretName)
#
# Lab-only. Re-run to rotate. PEMs are committed in plaintext alongside this
# script's output — do not port the pattern outside of perf test clusters.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORK="$(mktemp -d)"
trap "rm -rf $WORK" EXIT

cd "$WORK"

# CA
openssl genrsa -out ca.key 2048 2>/dev/null
openssl req -x509 -new -nodes -key ca.key -sha256 -days 3650 \
  -subj "/CN=mojaloop-perf-lab-ca" -out ca.crt

# Leaf with SANs
openssl genrsa -out leaf.key 2048 2>/dev/null
cat > csr.conf <<'EOF'
[req]
distinguished_name = dn
req_extensions     = req_ext
prompt             = no

[dn]
CN = mojaloop-perf-mtls

[req_ext]
keyUsage         = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth
subjectAltName   = @alt_names

[alt_names]
DNS.1  = account-lookup-service.local
DNS.2  = quoting-service.local
DNS.3  = ml-api-adapter.local
DNS.4  = sim-fsp201.local
DNS.5  = sim-fsp202.local
DNS.6  = sim-fsp203.local
DNS.7  = sim-fsp204.local
DNS.8  = sim-fsp205.local
DNS.9  = sim-fsp206.local
DNS.10 = sim-fsp207.local
DNS.11 = sim-fsp208.local
EOF

openssl req -new -key leaf.key -out leaf.csr -config csr.conf
openssl x509 -req -in leaf.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
  -out leaf.crt -days 3650 -sha256 -extfile csr.conf -extensions req_ext 2>/dev/null

CA_B64=$(base64 < ca.crt  | tr -d '\n')
CRT_B64=$(base64 < leaf.crt | tr -d '\n')
KEY_B64=$(base64 < leaf.key | tr -d '\n')

cat > "${SCRIPT_DIR}/04-switch-tls-secret.yaml" <<EOF
# Generated by regen-certs.sh — do not edit by hand.
# Referenced by 05-switch-inbound-mtls.yaml (Gateway credentialName) and,
# after being copied to the mojaloop namespace, by 07-switch-outbound-mtls.yaml
# (DestinationRule credentialName).
apiVersion: v1
kind: Secret
metadata:
  name: switch-mtls-creds
  namespace: istio-system
  labels: { app: mtls-lab }
type: kubernetes.io/tls
data:
  ca.crt:  ${CA_B64}
  tls.crt: ${CRT_B64}
  tls.key: ${KEY_B64}
EOF

cat > "${SCRIPT_DIR}/04-dfsp-tls-secret.yaml" <<EOF
# Generated by regen-certs.sh — do not edit by hand.
# Applied to the dfsps namespace on every DFSP cluster. The mojaloop-simulator
# Helm chart mounts this as /secrets/* when values set
# simulators.fspNNN.config.schemeAdapter.secrets.tlsSecretName: mtls-shared-creds
apiVersion: v1
kind: Secret
metadata:
  name: mtls-shared-creds
  namespace: dfsps
  labels: { app: mtls-lab }
type: Opaque
data:
  inbound-cacert.pem:  ${CA_B64}
  inbound-cert.pem:    ${CRT_B64}
  inbound-key.pem:     ${KEY_B64}
  outbound-cacert.pem: ${CA_B64}
  outbound-cert.pem:   ${CRT_B64}
  outbound-key.pem:    ${KEY_B64}
EOF

echo "Wrote:"
echo "  ${SCRIPT_DIR}/04-switch-tls-secret.yaml"
echo "  ${SCRIPT_DIR}/04-dfsp-tls-secret.yaml"
echo ""
echo "Leaf cert summary:"
openssl x509 -in leaf.crt -noout -subject -issuer -ext subjectAltName
