apiVersion: v1
kind: Pod
metadata:
  name: curl-k6-test
  namespace: k6-test
spec:
  containers:
    - name: curl
      image: curlimages/curl:8.10.1
      command: ["sleep", "3600"]
      imagePullPolicy: IfNotPresent
  restartPolicy: Always